import type { Vehicle } from '@drivewise/contracts';

import { buildExternalLinks } from '../../domain/external-links';

/**
 * Curated Danish-market inventory used by the in-memory repository.
 * Mirrors the design's twelve EVs and adds petrol/diesel/hybrid/PHEV and a
 * tax-free commercial van so every browse filter has data to bite on.
 * Replace with a Drizzle/Postgres adapter + ingestion pipeline in production.
 */

type SeedInput = Omit<Vehicle, 'externalLinks'>;

const vehicle = (input: SeedInput): Vehicle => ({
  ...input,
  externalLinks: buildExternalLinks(input.make, input.model, input.condition),
});

const uuid = (n: number): string =>
  `c1a6e2b0-0000-4000-8000-${String(n).padStart(12, '0')}`;

export const DANISH_VEHICLES: Vehicle[] = [
  vehicle({
    id: uuid(1),
    make: 'Volvo',
    model: 'EX40',
    variant: 'Recharge Twin',
    year: 2025,
    condition: 'new',
    bodyType: 'suv',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'awd',
    priceDkk: 419000,
    monthlyLeaseDkk: 4890,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 460,
    batteryKwh: 78,
    chargeMinutes10To80: 28,
    dcChargeKw: 155,
    consumptionKwhPer100Km: 18.9,
    consumptionLPer100Km: null,
    accelerationSec0To100: 4.8,
    topSpeedKmh: 180,
    cargoLiters: 419,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'A compact premium EV with Volvo build quality and class-leading safety tech. Range is mid-pack but the cabin punches above its size.',
    pros: ['Excellent safety tech', 'Premium cabin quality', 'Compact footprint for city use'],
    cons: ['Mid-pack range', 'Firm ride on larger wheels'],
    listedAt: '2026-06-28T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(2),
    make: 'Tesla',
    model: 'Model Y',
    variant: 'Long Range AWD',
    year: 2025,
    condition: 'new',
    bodyType: 'suv',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'awd',
    priceDkk: 389000,
    monthlyLeaseDkk: 4490,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 533,
    batteryKwh: 81,
    chargeMinutes10To80: 25,
    dcChargeKw: 250,
    consumptionKwhPer100Km: 16.9,
    consumptionLPer100Km: null,
    accelerationSec0To100: 4.3,
    topSpeedKmh: 217,
    cargoLiters: 854,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The benchmark long-range EV crossover. Unmatched charging convenience and software, with the largest cargo in its class.',
    pros: ['Best-in-class range', 'Supercharger network', 'Over-the-air software updates'],
    cons: ['Polarizing interior', 'Build consistency varies'],
    listedAt: '2026-07-02T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(3),
    make: 'Kia',
    model: 'EV6',
    variant: 'GT-Line AWD',
    year: 2025,
    condition: 'new',
    bodyType: 'crossover',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'awd',
    priceDkk: 359000,
    monthlyLeaseDkk: 4190,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 506,
    batteryKwh: 77,
    chargeMinutes10To80: 18,
    dcChargeKw: 240,
    consumptionKwhPer100Km: 17.2,
    consumptionLPer100Km: null,
    accelerationSec0To100: 5.2,
    topSpeedKmh: 185,
    cargoLiters: 480,
    euroNcapStars: 5,
    region: 'midtjylland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      '800V architecture gives the EV6 the fastest charging of its price class — 10 to 80 % in 18 minutes — wrapped in a striking design.',
    pros: ['Fastest charging in class', '7-year warranty', 'Distinctive design'],
    cons: ['Rear visibility', 'Infotainment learning curve'],
    listedAt: '2026-06-25T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(4),
    make: 'BMW',
    model: 'i4',
    variant: 'eDrive40',
    year: 2022,
    condition: 'used',
    bodyType: 'sedan',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 289000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 34000,
    seats: 5,
    doors: 5,
    evRangeKm: 550,
    batteryKwh: 84,
    chargeMinutes10To80: 31,
    dcChargeKw: 205,
    consumptionKwhPer100Km: 18.0,
    consumptionLPer100Km: null,
    accelerationSec0To100: 5.7,
    topSpeedKmh: 190,
    cargoLiters: 470,
    euroNcapStars: 5,
    region: 'sjaelland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'A driver-focused electric gran coupé. This 2022 example has modest mileage and the desirable eDrive40 long-range battery.',
    pros: ['Superb driving dynamics', 'Long real-world range', 'Quality interior'],
    cons: ['Tight rear headroom', 'No frunk'],
    listedAt: '2026-06-18T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(5),
    make: 'Hyundai',
    model: 'IONIQ 5',
    variant: 'Long Range RWD',
    year: 2023,
    condition: 'used',
    bodyType: 'crossover',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 269000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 18500,
    seats: 5,
    doors: 5,
    evRangeKm: 481,
    batteryKwh: 77.4,
    chargeMinutes10To80: 18,
    dcChargeKw: 233,
    consumptionKwhPer100Km: 17.9,
    consumptionLPer100Km: null,
    accelerationSec0To100: 7.3,
    topSpeedKmh: 185,
    cargoLiters: 527,
    euroNcapStars: 5,
    region: 'syddanmark',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'Retro-futuristic crossover with a lounge-like flat floor cabin and 800V ultra-fast charging. Low mileage for the year.',
    pros: ['Ultra-fast charging', 'Spacious flat-floor cabin', 'V2L power output'],
    cons: ['Soft handling', 'No rear wiper'],
    listedAt: '2026-06-20T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(6),
    make: 'Polestar',
    model: '2',
    variant: 'Long Range Single Motor',
    year: 2025,
    condition: 'new',
    bodyType: 'fastback',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 379000,
    monthlyLeaseDkk: 4390,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 655,
    batteryKwh: 82,
    chargeMinutes10To80: 28,
    dcChargeKw: 205,
    consumptionKwhPer100Km: 16.8,
    consumptionLPer100Km: null,
    accelerationSec0To100: 6.2,
    topSpeedKmh: 205,
    cargoLiters: 405,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The 2025 rear-drive update turned the Polestar 2 into a range champion — 655 km WLTP — with Scandinavian minimalist design.',
    pros: ['Class-leading range', 'Android Automotive built in', 'Understated design'],
    cons: ['Firm ride', 'Modest cargo space'],
    listedAt: '2026-07-01T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(7),
    make: 'Volkswagen',
    model: 'ID.4',
    variant: 'GTX',
    year: 2025,
    condition: 'new',
    bodyType: 'suv',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'awd',
    priceDkk: 369000,
    monthlyLeaseDkk: 4290,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 516,
    batteryKwh: 77,
    chargeMinutes10To80: 28,
    dcChargeKw: 175,
    consumptionKwhPer100Km: 18.2,
    consumptionLPer100Km: null,
    accelerationSec0To100: 5.4,
    topSpeedKmh: 180,
    cargoLiters: 543,
    euroNcapStars: 5,
    region: 'midtjylland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The performance-oriented dual-motor ID.4. A sensible family SUV with usable range, big boot and all-wheel-drive security.',
    pros: ['Practical family package', 'AWD traction', 'Comfortable ride'],
    cons: ['Fiddly haptic controls', 'Average charging speed'],
    listedAt: '2026-06-22T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(8),
    make: 'Mercedes-Benz',
    model: 'EQE',
    variant: '350+',
    year: 2025,
    condition: 'new',
    bodyType: 'sedan',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 689000,
    monthlyLeaseDkk: 7490,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 620,
    batteryKwh: 89,
    chargeMinutes10To80: 32,
    dcChargeKw: 170,
    consumptionKwhPer100Km: 17.2,
    consumptionLPer100Km: null,
    accelerationSec0To100: 6.4,
    topSpeedKmh: 210,
    cargoLiters: 430,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'A serene electric business sedan with limousine refinement, 620 km of range and Mercedes cabin craftsmanship.',
    pros: ['Exceptional comfort', 'Long range', 'Hyperscreen tech'],
    cons: ['Premium price', 'Limited rear visibility'],
    listedAt: '2026-06-15T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(9),
    make: 'MG',
    model: '4',
    variant: 'Trophy',
    year: 2025,
    condition: 'new',
    bodyType: 'hatchback',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 269000,
    monthlyLeaseDkk: 2990,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 435,
    batteryKwh: 64,
    chargeMinutes10To80: 26,
    dcChargeKw: 135,
    consumptionKwhPer100Km: 16.6,
    consumptionLPer100Km: null,
    accelerationSec0To100: 7.7,
    topSpeedKmh: 160,
    cargoLiters: 363,
    euroNcapStars: 5,
    region: 'nordjylland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The value pick: a genuinely fun rear-drive electric hatchback with a full equipment list at a price others cannot match.',
    pros: ['Outstanding value', 'Agile rear-drive chassis', 'Full equipment as standard'],
    cons: ['Average infotainment', 'Firm rear seats'],
    listedAt: '2026-06-30T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(10),
    make: 'Audi',
    model: 'Q4 e-tron',
    variant: '45',
    year: 2025,
    condition: 'new',
    bodyType: 'suv',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 449000,
    monthlyLeaseDkk: 5190,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: 559,
    batteryKwh: 77,
    chargeMinutes10To80: 28,
    dcChargeKw: 175,
    consumptionKwhPer100Km: 17.9,
    consumptionLPer100Km: null,
    accelerationSec0To100: 6.7,
    topSpeedKmh: 180,
    cargoLiters: 520,
    euroNcapStars: 5,
    region: 'syddanmark',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'Audi polish on the VW Group electric platform: hushed cabin, solid range and a premium badge without the premium-plus price.',
    pros: ['Refined quiet cabin', 'Solid real-world range', 'Strong resale value'],
    cons: ['Options add up quickly', 'Uninvolving to drive'],
    listedAt: '2026-06-26T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(11),
    make: 'Škoda',
    model: 'Enyaq',
    variant: '85',
    year: 2021,
    condition: 'used',
    bodyType: 'suv',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 219000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 52000,
    seats: 5,
    doors: 5,
    evRangeKm: 520,
    batteryKwh: 77,
    chargeMinutes10To80: 29,
    dcChargeKw: 135,
    consumptionKwhPer100Km: 16.8,
    consumptionLPer100Km: null,
    accelerationSec0To100: 8.5,
    topSpeedKmh: 160,
    cargoLiters: 585,
    euroNcapStars: 5,
    region: 'fyn',
    sellerType: 'private',
    imageUrl: null,
    summary:
      'A sensibly priced family EV with one of the biggest boots in the class. Privately sold with full service history.',
    pros: ['Huge boot', 'Efficient in mixed driving', 'Simply clever storage'],
    cons: ['Slower DC charging', 'Higher mileage'],
    listedAt: '2026-06-10T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(12),
    make: 'Tesla',
    model: 'Model 3',
    variant: 'Long Range AWD',
    year: 2024,
    condition: 'used',
    bodyType: 'sedan',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'awd',
    priceDkk: 329000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 9200,
    seats: 5,
    doors: 5,
    evRangeKm: 629,
    batteryKwh: 75,
    chargeMinutes10To80: 27,
    dcChargeKw: 250,
    consumptionKwhPer100Km: 14.0,
    consumptionLPer100Km: null,
    accelerationSec0To100: 4.4,
    topSpeedKmh: 201,
    cargoLiters: 594,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'private',
    imageUrl: null,
    summary:
      'Nearly-new Highland Model 3 with the long-range battery — 629 km WLTP and the efficiency crown, at a used-car price.',
    pros: ['Exceptional efficiency', 'Nearly new condition', 'Supercharger access'],
    cons: ['Stalkless controls divide opinion', 'Firm low-speed ride'],
    listedAt: '2026-07-04T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(13),
    make: 'Toyota',
    model: 'Corolla Touring Sports',
    variant: '1.8 Hybrid Active',
    year: 2025,
    condition: 'new',
    bodyType: 'stationcar',
    fuelType: 'hybrid',
    transmission: 'automatic',
    drivetrain: 'fwd',
    priceDkk: 289000,
    monthlyLeaseDkk: 3290,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: null,
    batteryKwh: null,
    chargeMinutes10To80: null,
    dcChargeKw: null,
    consumptionKwhPer100Km: null,
    consumptionLPer100Km: 4.5,
    accelerationSec0To100: 9.1,
    topSpeedKmh: 180,
    cargoLiters: 581,
    euroNcapStars: 5,
    region: 'midtjylland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The dependable choice: a self-charging hybrid estate with Toyota reliability, 4.5 l/100 km and a big practical boot.',
    pros: ['Proven reliability', 'Low fuel consumption', 'No charging needed'],
    cons: ['CVT drone under load', 'Modest performance'],
    listedAt: '2026-06-24T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(14),
    make: 'Volkswagen',
    model: 'Golf',
    variant: '1.5 TSI Style',
    year: 2021,
    condition: 'used',
    bodyType: 'hatchback',
    fuelType: 'petrol',
    transmission: 'manual',
    drivetrain: 'fwd',
    priceDkk: 189000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 61000,
    seats: 5,
    doors: 5,
    evRangeKm: null,
    batteryKwh: null,
    chargeMinutes10To80: null,
    dcChargeKw: null,
    consumptionKwhPer100Km: null,
    consumptionLPer100Km: 5.6,
    accelerationSec0To100: 8.5,
    topSpeedKmh: 224,
    cargoLiters: 380,
    euroNcapStars: 5,
    region: 'sjaelland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The all-rounder benchmark. A well-kept Golf 8 with the sweet-spot 1.5 TSI engine and a slick manual gearbox.',
    pros: ['Balanced to drive', 'Cheap to run', 'Strong dealer network'],
    cons: ['Frustrating touch controls', 'Cabin plastics below par'],
    listedAt: '2026-06-12T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(15),
    make: 'Peugeot',
    model: '208',
    variant: '1.2 PureTech Allure',
    year: 2022,
    condition: 'used',
    bodyType: 'hatchback',
    fuelType: 'petrol',
    transmission: 'manual',
    drivetrain: 'fwd',
    priceDkk: 129000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 38000,
    seats: 5,
    doors: 5,
    evRangeKm: null,
    batteryKwh: null,
    chargeMinutes10To80: null,
    dcChargeKw: null,
    consumptionKwhPer100Km: null,
    consumptionLPer100Km: 4.9,
    accelerationSec0To100: 9.9,
    topSpeedKmh: 188,
    cargoLiters: 311,
    euroNcapStars: 4,
    region: 'nordjylland',
    sellerType: 'private',
    imageUrl: null,
    summary:
      'A stylish first car or city runabout. Frugal three-cylinder petrol, distinctive design, sold privately at a sharp price.',
    pros: ['Low running costs', 'Chic interior design', 'Easy to park'],
    cons: ['Small rear seats', 'i-Cockpit not for everyone'],
    listedAt: '2026-06-08T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(16),
    make: 'Škoda',
    model: 'Octavia Combi',
    variant: '2.0 TDI Style DSG',
    year: 2020,
    condition: 'used',
    bodyType: 'stationcar',
    fuelType: 'diesel',
    transmission: 'automatic',
    drivetrain: 'fwd',
    priceDkk: 179000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 98000,
    seats: 5,
    doors: 5,
    evRangeKm: null,
    batteryKwh: null,
    chargeMinutes10To80: null,
    dcChargeKw: null,
    consumptionKwhPer100Km: null,
    consumptionLPer100Km: 4.4,
    accelerationSec0To100: 8.8,
    topSpeedKmh: 223,
    cargoLiters: 640,
    euroNcapStars: 5,
    region: 'syddanmark',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The motorway kilometre-eater: a 640-litre boot and 4.4 l/100 km diesel economy make this the long-distance value pick.',
    pros: ['Enormous boot', 'Frugal on the motorway', 'Comfortable cruiser'],
    cons: ['Higher mileage', 'Diesel city restrictions may tighten'],
    listedAt: '2026-06-05T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(17),
    make: 'Toyota',
    model: 'Yaris Cross',
    variant: 'Hybrid Style',
    year: 2025,
    condition: 'new',
    bodyType: 'crossover',
    fuelType: 'hybrid',
    transmission: 'automatic',
    drivetrain: 'fwd',
    priceDkk: 259000,
    monthlyLeaseDkk: 2790,
    registrationTaxPaid: true,
    mileageKm: null,
    seats: 5,
    doors: 5,
    evRangeKm: null,
    batteryKwh: null,
    chargeMinutes10To80: null,
    dcChargeKw: null,
    consumptionKwhPer100Km: null,
    consumptionLPer100Km: 4.4,
    accelerationSec0To100: 11.2,
    topSpeedKmh: 170,
    cargoLiters: 397,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'A compact hybrid crossover that sips fuel in the city. High driving position and Toyota dependability in a small footprint.',
    pros: ['Very low city consumption', 'Elevated driving position', 'Compact and easy to park'],
    cons: ['Noisy at full throttle', 'Rear space is tight'],
    listedAt: '2026-06-29T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(18),
    make: 'Ford',
    model: 'Kuga',
    variant: '2.5 PHEV Titanium',
    year: 2023,
    condition: 'used',
    bodyType: 'suv',
    fuelType: 'phev',
    transmission: 'automatic',
    drivetrain: 'fwd',
    priceDkk: 279000,
    monthlyLeaseDkk: null,
    registrationTaxPaid: true,
    mileageKm: 27000,
    seats: 5,
    doors: 5,
    evRangeKm: 64,
    batteryKwh: 14.4,
    chargeMinutes10To80: null,
    dcChargeKw: null,
    consumptionKwhPer100Km: 17.0,
    consumptionLPer100Km: 5.8,
    accelerationSec0To100: 9.2,
    topSpeedKmh: 200,
    cargoLiters: 412,
    euroNcapStars: 5,
    region: 'midtjylland',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'Plug-in hybrid family SUV: 64 km of electric commuting with petrol backup for the holidays. The best of both for transition buyers.',
    pros: ['64 km electric range', 'No range anxiety', 'Roomy family SUV'],
    cons: ['Heavier than pure ICE', 'Needs charging to make sense'],
    listedAt: '2026-06-16T09:00:00.000Z',
  }),
  vehicle({
    id: uuid(19),
    make: 'Volkswagen',
    model: 'ID. Buzz',
    variant: 'Cargo',
    year: 2025,
    condition: 'new',
    bodyType: 'van',
    fuelType: 'ev',
    transmission: 'automatic',
    drivetrain: 'rwd',
    priceDkk: 339000,
    monthlyLeaseDkk: 4590,
    registrationTaxPaid: false,
    mileageKm: null,
    seats: 3,
    doors: 4,
    evRangeKm: 425,
    batteryKwh: 79,
    chargeMinutes10To80: 26,
    dcChargeKw: 185,
    consumptionKwhPer100Km: 21.5,
    consumptionLPer100Km: null,
    accelerationSec0To100: 10.2,
    topSpeedKmh: 160,
    cargoLiters: 3900,
    euroNcapStars: 5,
    region: 'hovedstaden',
    sellerType: 'dealer',
    imageUrl: null,
    summary:
      'The electric workhorse on yellow plates — sold without registration tax for commercial use. 3.9 m³ of cargo and iconic looks.',
    pros: ['Tax-free commercial pricing', 'Huge cargo volume', 'Head-turning design'],
    cons: ['Three seats only', 'Higher consumption'],
    listedAt: '2026-07-03T09:00:00.000Z',
  }),
];
